###create user
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Luca Watson"
}


###create course
POST http://localhost:3333/courses
Content-Type: application/json

{
  "name": "Curso de C"
}


###list users
GET http://localhost:3333/users


###list courses
GET http://localhost:3333/courses


###create registration
POST http://localhost:3333/registration
Content-Type: application/json

{
  "user_id": "7a1a2533-11b4-46ab-bc44-0116643d9b91",
  "course_id": "938ac966-6a64-4203-b0a7-0c1d95823f63"
}


###create progress
POST http://localhost:3333/progress
Content-Type: application/json

{
  "user_id": "7a1a2533-11b4-46ab-bc44-0116643d9b91",
  "course_id": "938ac966-6a64-4203-b0a7-0c1d95823f63",
  "registration_id": "a6143dbd-599e-450b-bfd1-863186dfd30b",
  "percentage": 15
}

###update progress
PUT http://localhost:3333/progress/update
Content-Type: application/json

{
  "user_id": "7a1a2533-11b4-46ab-bc44-0116643d9b91",
  "course_id": "938ac966-6a64-4203-b0a7-0c1d95823f63",
  "registration_id": "a6143dbd-599e-450b-bfd1-863186dfd30b",
  "percentage": 8
}


###get progress by user_id
GET http://localhost:3333/progress/07042196-265e-4965-826f-9bd25809119f


###usuários de um curso (user_id)
GET http://localhost:3333/courses/938ac966-6a64-4203-b0a7-0c1d95823f63


###cursos de um usuário (user_id)
GET http://localhost:3333/courses/user/5baa52ed-2c8f-4d59-aa09-64eafc1ad4df


###média de progresso e cursos terminados(resumo)
GET http://localhost:3333/courses/progress/7a1a2533-11b4-46ab-bc44-0116643d9b91

###ranking  de usuários por média de progresso
GET http://localhost:3333/users/ranking
